import { describe, expect, it } from 'vitest'
import * as falsestart from './index.ts'

describe('library surface', () => {
  it('exposes the pipeline as separable steps', () => {
    // Named individually rather than snapshotted: removing one of these is a breaking change for
    // a consumer, and it should have to be spelled out here before it can happen.
    expect(Object.keys(falsestart).toSorted()).toEqual([
      'BaselineUnreadable',
      'ConfigError',
      'DEFAULT_CONFIG_CANDIDATES',
      'DEFAULT_EXCLUSIONS',
      'JAVASCRIPT_EXTENSIONS',
      'MatchError',
      'RuleLoadError',
      'RuleParseError',
      'SEVERITIES',
      'SHIPPED_RULE_IDS',
      'SOURCE_EXTENSIONS',
      'SUPPORTED_LANGUAGES',
      'ScanError',
      'ScanExit',
      'TYPESCRIPT_EXTENSIONS',
      'WRITE_TOOLS',
      'appliesTo',
      'applyScopeOverrides',
      'assessRule',
      'baselineText',
      'checkFile',
      'decide',
      'diagnose',
      'extensionGlobGroup',
      'fallbacks',
      'findDefaultConfigs',
      'findNarrowedScopes',
      'findUntestedRules',
      'findViolations',
      'findViolationsIn',
      'fingerprint',
      'grammarFor',
      'judgesPayload',
      'loadConfigFile',
      'loadDefaultConfig',
      'loadRules',
      'makeConfig',
      'makeConfigUnsafe',
      'matchesAny',
      'parseConfig',
      'parseIgnoredPaths',
      'parseRule',
      'parseSource',
      'partitionPaths',
      'readBaseline',
      'readBaselineText',
      'render',
      'respond',
      'samplePath',
      'scan',
      'toScopingPath',
      'validateConfig',
      'writeBaseline',
    ])
  })
})
